class A
  # A compex class
  #
  attr_accessor :aa
  attr_accessor :ab
  attr_accessor :ac
  attr_accessor :ad
  attr_accessor :ae
  attr_accessor :af
  attr_accessor :ag
  attr_accessor :ah
  attr_accessor :ai
  attr_accessor :aj
  attr_accessor :ak
  attr_accessor :al
  attr_accessor :am
  attr_accessor :an
  attr_accessor :ao
  attr_accessor :ap
  attr_accessor :aq
  attr_accessor :ar
  attr_accessor :as
  attr_accessor :at
  attr_accessor :au
  attr_accessor :av
  attr_accessor :aw
  attr_accessor :ax
  attr_accessor :ay
  attr_accessor :az
  attr_accessor :ba
  attr_accessor :bb
  attr_accessor :bc
  attr_accessor :bd
  attr_accessor :be
  attr_accessor :bf
  attr_accessor :bg
  attr_accessor :bh
  attr_accessor :bi
  attr_accessor :bj
  attr_accessor :bk
  attr_accessor :bl
  attr_accessor :bm
  attr_accessor :bn
  attr_accessor :bo
  attr_accessor :bp
  attr_accessor :bq
  attr_accessor :br
  attr_accessor :bs
  attr_accessor :bt
  attr_accessor :bu
  attr_accessor :bv
  attr_accessor :bw
  attr_accessor :bx
  attr_accessor :by
  attr_accessor :bz
  attr_accessor :ca
  attr_accessor :cb
  attr_accessor :cc
  attr_accessor :cd
  attr_accessor :ce
  attr_accessor :cf
  attr_accessor :cg
  attr_accessor :ch
  attr_accessor :ci
  attr_accessor :cj
  attr_accessor :ck
  attr_accessor :cl
  attr_accessor :cm
  attr_accessor :cn
  attr_accessor :co
  attr_accessor :cp
  attr_accessor :cq
  attr_accessor :cr
  attr_accessor :cs
  attr_accessor :ct
  attr_accessor :cu
  attr_accessor :cv
  attr_accessor :cw
  attr_accessor :cx
  attr_accessor :cy
  attr_accessor :cz
  attr_accessor :da
  attr_accessor :db
  attr_accessor :dc
  attr_accessor :dd
  attr_accessor :de
  attr_accessor :df
  attr_accessor :dg
  attr_accessor :dh
  attr_accessor :di
  attr_accessor :dj
  attr_accessor :dk
  attr_accessor :dl
  attr_accessor :dm
  attr_accessor :dn
  attr_accessor :do
  attr_accessor :dp
  attr_accessor :dq
  attr_accessor :dr
  attr_accessor :ds
  attr_accessor :dt
  attr_accessor :du
  attr_accessor :dv
  attr_accessor :dw
  attr_accessor :dx
  attr_accessor :dy
  attr_accessor :dz
  attr_accessor :ea
  attr_accessor :eb
  attr_accessor :ec
  attr_accessor :ed
  attr_accessor :ee
  attr_accessor :ef
  attr_accessor :eg
  attr_accessor :eh
  attr_accessor :ei
  attr_accessor :ej
  attr_accessor :ek
  attr_accessor :el
  attr_accessor :em
  attr_accessor :en
  attr_accessor :eo
  attr_accessor :ep
  attr_accessor :eq
  attr_accessor :er
  attr_accessor :es
  attr_accessor :et
  attr_accessor :eu
  attr_accessor :ev
  attr_accessor :ew
  attr_accessor :ex
  attr_accessor :ey
  attr_accessor :ez
  attr_accessor :fa
  attr_accessor :fb
  attr_accessor :fc
  attr_accessor :fd
  attr_accessor :fe
  attr_accessor :ff
  attr_accessor :fg
  attr_accessor :fh
  attr_accessor :fi
  attr_accessor :fj
  attr_accessor :fk
  attr_accessor :fl
  attr_accessor :fm
  attr_accessor :fn
  attr_accessor :fo
  attr_accessor :fp
  attr_accessor :fq
  attr_accessor :fr
  attr_accessor :fs
  attr_accessor :ft
  attr_accessor :fu
  attr_accessor :fv
  attr_accessor :fw
  attr_accessor :fx
  attr_accessor :fy
  attr_accessor :fz
  attr_accessor :ga
  attr_accessor :gb
  attr_accessor :gc
  attr_accessor :gd
  attr_accessor :ge
  attr_accessor :gf
  attr_accessor :gg
  attr_accessor :gh
  attr_accessor :gi
  attr_accessor :gj
  attr_accessor :gk
  attr_accessor :gl
  attr_accessor :gm
  attr_accessor :gn
  attr_accessor :go
  attr_accessor :gp
  attr_accessor :gq
  attr_accessor :gr
  attr_accessor :gs
  attr_accessor :gt
  attr_accessor :gu
  attr_accessor :gv
  attr_accessor :gw
  attr_accessor :gx
  attr_accessor :gy
  attr_accessor :gz
  attr_accessor :ha
  attr_accessor :hb
  attr_accessor :hc
  attr_accessor :hd
  attr_accessor :he
  attr_accessor :hf
  attr_accessor :hg
  attr_accessor :hh
  attr_accessor :hi
  attr_accessor :hj
  attr_accessor :hk
  attr_accessor :hl
  attr_accessor :hm
  attr_accessor :hn
  attr_accessor :ho
  attr_accessor :hp
  attr_accessor :hq
  attr_accessor :hr
  attr_accessor :hs
  attr_accessor :ht
  attr_accessor :hu
  attr_accessor :hv
  attr_accessor :hw
  attr_accessor :hx
  attr_accessor :hy
  attr_accessor :hz
  attr_accessor :ia
  attr_accessor :ib
  attr_accessor :ic
  attr_accessor :id
  attr_accessor :ie
  attr_accessor :if
  attr_accessor :ig
  attr_accessor :ih
  attr_accessor :ii
  attr_accessor :ij
  attr_accessor :ik
  attr_accessor :il
  attr_accessor :im
  attr_accessor :in
  attr_accessor :io
  attr_accessor :ip
  attr_accessor :iq
  attr_accessor :ir
  attr_accessor :is
  attr_accessor :it
  attr_accessor :iu
  attr_accessor :iv
  attr_accessor :iw
  attr_accessor :ix
  attr_accessor :iy
  attr_accessor :iz
  attr_accessor :ja
  attr_accessor :jb
  attr_accessor :jc
  attr_accessor :jd
  attr_accessor :je
  attr_accessor :jf
  attr_accessor :jg
  attr_accessor :jh
  attr_accessor :ji
  attr_accessor :jj
  attr_accessor :jk
  attr_accessor :jl
  attr_accessor :jm
  attr_accessor :jn
  attr_accessor :jo
  attr_accessor :jp
  attr_accessor :jq
  attr_accessor :jr
  attr_accessor :js
  attr_accessor :jt
  attr_accessor :ju
  attr_accessor :jv
  attr_accessor :jw
  attr_accessor :jx
  attr_accessor :jy
  attr_accessor :jz
  attr_accessor :ka
  attr_accessor :kb
  attr_accessor :kc
  attr_accessor :kd
  attr_accessor :ke
  attr_accessor :kf
  attr_accessor :kg
  attr_accessor :kh
  attr_accessor :ki
  attr_accessor :kj
  attr_accessor :kk
  attr_accessor :kl
  attr_accessor :km
  attr_accessor :kn
  attr_accessor :ko
  attr_accessor :kp
  attr_accessor :kq
  attr_accessor :kr
  attr_accessor :ks
  attr_accessor :kt
  attr_accessor :ku
  attr_accessor :kv
  attr_accessor :kw
  attr_accessor :kx
  attr_accessor :ky
  attr_accessor :kz
  attr_accessor :la
  attr_accessor :lb
  attr_accessor :lc
  attr_accessor :ld
  attr_accessor :le
  attr_accessor :lf
  attr_accessor :lg
  attr_accessor :lh
  attr_accessor :li
  attr_accessor :lj
  attr_accessor :lk
  attr_accessor :ll
  attr_accessor :lm
  attr_accessor :ln
  attr_accessor :lo
  attr_accessor :lp
  attr_accessor :lq
  attr_accessor :lr
  attr_accessor :ls
  attr_accessor :lt
  attr_accessor :lu
  attr_accessor :lv
  attr_accessor :lw
  attr_accessor :lx
  attr_accessor :ly
  attr_accessor :lz
  attr_accessor :ma
  attr_accessor :mb
  attr_accessor :mc
  attr_accessor :md
  attr_accessor :me
  attr_accessor :mf
  attr_accessor :mg
  attr_accessor :mh
  attr_accessor :mi
  attr_accessor :mj
  attr_accessor :mk
  attr_accessor :ml
  attr_accessor :mm
  attr_accessor :mn
  attr_accessor :mo
  attr_accessor :mp
  attr_accessor :mq
  attr_accessor :mr
  attr_accessor :ms
  attr_accessor :mt
  attr_accessor :mu
  attr_accessor :mv
  attr_accessor :mw
  attr_accessor :mx
  attr_accessor :my
  attr_accessor :mz
  attr_accessor :na
  attr_accessor :nb
  attr_accessor :nc
  attr_accessor :nd
  attr_accessor :ne
  attr_accessor :nf
  attr_accessor :ng
  attr_accessor :nh
  attr_accessor :ni
  attr_accessor :nj
  attr_accessor :nk
  attr_accessor :nl
  attr_accessor :nm
  attr_accessor :nn
  attr_accessor :no
  attr_accessor :np
  attr_accessor :nq
  attr_accessor :nr
  attr_accessor :ns
  attr_accessor :nt
  attr_accessor :nu
  attr_accessor :nv
  attr_accessor :nw
  attr_accessor :nx
  attr_accessor :ny
  attr_accessor :nz
  attr_accessor :oa
  attr_accessor :ob
  attr_accessor :oc
  attr_accessor :od
  attr_accessor :oe
  attr_accessor :of
  attr_accessor :og
  attr_accessor :oh
  attr_accessor :oi
  attr_accessor :oj
  attr_accessor :ok
  attr_accessor :ol
  attr_accessor :om
  attr_accessor :on
  attr_accessor :oo
  attr_accessor :op
  attr_accessor :oq
  attr_accessor :or
  attr_accessor :os
  attr_accessor :ot
  attr_accessor :ou
  attr_accessor :ov
  attr_accessor :ow
  attr_accessor :ox
  attr_accessor :oy
  attr_accessor :oz
  attr_accessor :pa
  attr_accessor :pb
  attr_accessor :pc
  attr_accessor :pd
  attr_accessor :pe
  attr_accessor :pf
  attr_accessor :pg
  attr_accessor :ph
  attr_accessor :pi
  attr_accessor :pj
  attr_accessor :pk
  attr_accessor :pl
  attr_accessor :pm
  attr_accessor :pn
  attr_accessor :po
  attr_accessor :pp
  attr_accessor :pq
  attr_accessor :pr
  attr_accessor :ps
  attr_accessor :pt
  attr_accessor :pu
  attr_accessor :pv
  attr_accessor :pw
  attr_accessor :px
  attr_accessor :py
  attr_accessor :pz
  attr_accessor :qa
  attr_accessor :qb
  attr_accessor :qc
  attr_accessor :qd
  attr_accessor :qe
  attr_accessor :qf
  attr_accessor :qg
  attr_accessor :qh
  attr_accessor :qi
  attr_accessor :qj
  attr_accessor :qk
  attr_accessor :ql
  attr_accessor :qm
  attr_accessor :qn
  attr_accessor :qo
  attr_accessor :qp
  attr_accessor :qq
  attr_accessor :qr
  attr_accessor :qs
  attr_accessor :qt
  attr_accessor :qu
  attr_accessor :qv
  attr_accessor :qw
  attr_accessor :qx
  attr_accessor :qy
  attr_accessor :qz
  attr_accessor :ra
  attr_accessor :rb
  attr_accessor :rc
  attr_accessor :rd
  attr_accessor :re
  attr_accessor :rf
  attr_accessor :rg
  attr_accessor :rh
  attr_accessor :ri
  attr_accessor :rj
  attr_accessor :rk
  attr_accessor :rl
  attr_accessor :rm
  attr_accessor :rn
  attr_accessor :ro
  attr_accessor :rp
  attr_accessor :rq
  attr_accessor :rr
  attr_accessor :rs
  attr_accessor :rt
  attr_accessor :ru
  attr_accessor :rv
  attr_accessor :rw
  attr_accessor :rx
  attr_accessor :ry
  attr_accessor :rz
  attr_accessor :sa
  attr_accessor :sb
  attr_accessor :sc
  attr_accessor :sd
  attr_accessor :se
  attr_accessor :sf
  attr_accessor :sg
  attr_accessor :sh
  attr_accessor :si
  attr_accessor :sj
  attr_accessor :sk
  attr_accessor :sl
  attr_accessor :sm
  attr_accessor :sn
  attr_accessor :so
  attr_accessor :sp
  attr_accessor :sq
  attr_accessor :sr
  attr_accessor :ss
  attr_accessor :st
  attr_accessor :su
  attr_accessor :sv
  attr_accessor :sw
  attr_accessor :sx
  attr_accessor :sy
  attr_accessor :sz
  attr_accessor :ta
  attr_accessor :tb
  attr_accessor :tc
  attr_accessor :td
  attr_accessor :te
  attr_accessor :tf
  attr_accessor :tg
  attr_accessor :th
  attr_accessor :ti
  attr_accessor :tj
  attr_accessor :tk
  attr_accessor :tl
  attr_accessor :tm
  attr_accessor :tn
  attr_accessor :to
  attr_accessor :tp
  attr_accessor :tq
  attr_accessor :tr
  attr_accessor :ts
  attr_accessor :tt
  attr_accessor :tu
  attr_accessor :tv
  attr_accessor :tw
  attr_accessor :tx
  attr_accessor :ty
  attr_accessor :tz
  attr_accessor :ua
  attr_accessor :ub
  attr_accessor :uc
  attr_accessor :ud
  attr_accessor :ue
  attr_accessor :uf
  attr_accessor :ug
  attr_accessor :uh
  attr_accessor :ui
  attr_accessor :uj
  attr_accessor :uk
  attr_accessor :ul
  attr_accessor :um
  attr_accessor :un
  attr_accessor :uo
  attr_accessor :up
  attr_accessor :uq
  attr_accessor :ur
  attr_accessor :us
  attr_accessor :ut
  attr_accessor :uu
  attr_accessor :uv
  attr_accessor :uw
  attr_accessor :ux
  attr_accessor :uy
  attr_accessor :uz
  attr_accessor :va
  attr_accessor :vb
  attr_accessor :vc
  attr_accessor :vd
  attr_accessor :ve
  attr_accessor :vf
  attr_accessor :vg
  attr_accessor :vh
  attr_accessor :vi
  attr_accessor :vj
  attr_accessor :vk
  attr_accessor :vl
  attr_accessor :vm
  attr_accessor :vn
  attr_accessor :vo
  attr_accessor :vp
  attr_accessor :vq
  attr_accessor :vr
  attr_accessor :vs
  attr_accessor :vt
  attr_accessor :vu
  attr_accessor :vv
  attr_accessor :vw
  attr_accessor :vx
  attr_accessor :vy
  attr_accessor :vz
  attr_accessor :wa
  attr_accessor :wb
  attr_accessor :wc
  attr_accessor :wd
  attr_accessor :we
  attr_accessor :wf
  attr_accessor :wg
  attr_accessor :wh
  attr_accessor :wi
  attr_accessor :wj
  attr_accessor :wk
  attr_accessor :wl
  attr_accessor :wm
  attr_accessor :wn
  attr_accessor :wo
  attr_accessor :wp
  attr_accessor :wq
  attr_accessor :wr
  attr_accessor :ws
  attr_accessor :wt
  attr_accessor :wu
  attr_accessor :wv
  attr_accessor :ww
  attr_accessor :wx
  attr_accessor :wy
  attr_accessor :wz
  attr_accessor :xa
  attr_accessor :xb
  attr_accessor :xc
  attr_accessor :xd
  attr_accessor :xe
  attr_accessor :xf
  attr_accessor :xg
  attr_accessor :xh
  attr_accessor :xi
  attr_accessor :xj
  attr_accessor :xk
  attr_accessor :xl
  attr_accessor :xm
  attr_accessor :xn
  attr_accessor :xo
  attr_accessor :xp
  attr_accessor :xq
  attr_accessor :xr
  attr_accessor :xs
  attr_accessor :xt
  attr_accessor :xu
  attr_accessor :xv
  attr_accessor :xw
  attr_accessor :xx
  attr_accessor :xy
  attr_accessor :xz
  attr_accessor :ya
  attr_accessor :yb
  attr_accessor :yc
  attr_accessor :yd
  attr_accessor :ye
  attr_accessor :yf
  attr_accessor :yg
  attr_accessor :yh
  attr_accessor :yi
  attr_accessor :yj
  attr_accessor :yk
  attr_accessor :yl
  attr_accessor :ym
  attr_accessor :yn
  attr_accessor :yo
  attr_accessor :yp
  attr_accessor :yq
  attr_accessor :yr
  attr_accessor :ys
  attr_accessor :yt
  attr_accessor :yu
  attr_accessor :yv
  attr_accessor :yw
  attr_accessor :yx
  attr_accessor :yy
  attr_accessor :yz
  attr_accessor :za
  attr_accessor :zb
  attr_accessor :zc
  attr_accessor :zd
  attr_accessor :ze
  attr_accessor :zf
  attr_accessor :zg
  attr_accessor :zh
  attr_accessor :zi
  attr_accessor :zj
  attr_accessor :zk
  attr_accessor :zl
  attr_accessor :zm
  attr_accessor :zn
  attr_accessor :zo
  attr_accessor :zp
  attr_accessor :zq
  attr_accessor :zr
  attr_accessor :zs
  attr_accessor :zt
  attr_accessor :zu
  attr_accessor :zv
  attr_accessor :zw
  attr_accessor :zx
  attr_accessor :zy
  attr_accessor :zz

end
